### ISSUE TITLE
Support null-safety

### ISSUE THREAD

**Issue by IrinaSouth** [dart-ogurets/openapi_dart_common#2]

**Comment by federicoviceconti** [comment]
Same here. When will this library update?

**Comment by rvowles** [comment]
We're testing it now. There is a branch here called mods-for-nullsafe and the one in the openapi generator is support-nullsafe if you wish to test them together. You will need to do some manual patching.

**Comment by rvowles** [comment]
resolve with 4.0.0-prev1
