### ISSUE TITLE
openApiDateTimeParameterToString() url-encodes date strings which breaks with Dio since they get encoded twice

### ISSUE THREAD

**Issue by michpohl** [dart-ogurets/openapi_dart_common#7]
The function `openApiDateTimeParameterToString()` in `api_helper.dart` converts a `DateTime` object into a url-encoded string.

This is the method:
```
String openApiDateTimeParameterToString(dynamic value) {
  return Uri.encodeComponent((value as DateTime).toUtc().toIso8601String());
}
```

Now if I pass my complete request to `Dio` (with no further options specified) to query my backend API, the date string the backend receives looks like this : `2021-09-28T15%3A54%3A26.651199Z`
It seems to have been encoded twice, since `Dio` uses it's own encoder on the request.

If I remove the url-encoding (removing the `encodeComponent` part): 
```
String openApiDateTimeParameterToString(dynamic value) {
  return (value as DateTime).toUtc().toIso8601String();
}
```
I get a correctly url-encoded string in the request sent out by `Dio` 
 
So I'm wondering if this url-encoding should be removed  (happy to submit a PR if yes) or if there is any known place where I could have made a mistake that leads to this problem?

**Comment by rvowles** [comment]
Turn Dio logging on in your front end and see what it is actually doing, because we have people using this and it hasn't received any issues previously... I'd like to be really sure before issuing any changes.

**Comment by michpohl** [comment]
👍 Will do and report.

**Comment by michpohl** [comment]
Hi @rvowles,
I hope this will satisfy your needs - otherwise let me know!

We're using `DioClientDelegate` from this library, which gets initialized with a very basic `Dio` instance, that looks like this:
```
  static Dio makeDio() => Dio()
    ..options.receiveTimeout = 30000
    ..options.sendTimeout = 30000;
```

We used to use the openApi generater version 5.3 (`openapi_dart_common` 4.0.0), and just recently updated to the latest version (5.10/4.1.0), which now breaks our communication with the problem described above.
A dio backend request logged with an interceptor looks like this:
```
flutter: [DIO]--> GET https://mydomain.com/routing-service/journeys
?origin=blob%3ACAESDGhlcmU6ODAxMTExMxoSCQA3ixcLuypAEQ6IEFfOPEpAIAMqEEJlcmxpbiBTw7xka3JldXo%3D
&destination=blob%3ACAESKmhlcmU6aGVyZTphZjpzdHJlZXQ6SkVxVUVQdmVidUtWR1FVT2trNWlWQxoSCaJinL8JxSpAEUfJq3MMREpAIAIqDkFtIE5vcmRiYWhuaG9mMhgxMDExNSBCZXJsaW4sRGV1dHNjaGxhbmQ%3D
&date=2021-09-30T11%253A44%253A02.461385Z
&dateKind=departure
```

with my change described above the request is built as intended:
```
flutter: [DIO]--> GET https://mydomain.com/journeys
?origin=blob%3ACAESDGhlcmU6ODAxMTExMxoSCQA3ixcLuypAEQ6IEFfOPEpAIAMqEEJlcmxpbiBTw7xka3JldXo%3D
&destination=blob%3ACAESKmhlcmU6aGVyZTphZjpzdHJlZXQ6SkVxVUVQdmVidUtWR1FVT2trNWlWQxoSCaJinL8JxSpAEUfJq3MMREpAIAIqDkFtIE5vcmRiYWhuaG9mMhgxMDExNSBCZXJsaW4sRGV1dHNjaGxhbmQ%3D
&date=2021-09-30T11%3A44%3A02.461385Z
&dateKind=departure
```

( I've left parts of the request in there even if it's not related, just to give some context. The argument in question is of course the `date` entry.)

Of course it is possible there is something wrong on our end, but I wouldn't know where, given that there is nothing special happening and no extra processing anywhere...

**Comment by rvowles** [comment]
So this was a "fix" from 5.5 because of path parameters where it needed to be URL encoded: 

https://github.com/dart-ogurets/dart-openapi-maven/issues/34

So it isn't going to be a simple fix i'm sorry, i'll try and tackle it this weekend.

**Comment by michpohl** [comment]
Thank you for looking into it - Let me know if I can assist in any way (although I might not know enough about the whole topic).

In reference to the other issue that lead to the changes - I would assume since this conversion of a `DateTime` : `myDateTime.toUtc().toIso8601String()` returns a correct string representation of that object and is accepted and handled properly by `Dio`, there should be no further safeguarding necessary from your side. More custom cases could be handled in a customised implementation of `ApiClientDelegate` or via `Dio` options.
But as I said, I probably don't know enough about this to see the whole picture.

**Comment by rvowles** [comment]
I think its more that the path element needs to be encoded but the query parameter doesn't. And I'm using the same function for both, so I need to "stop doing that" :-)

**Comment by rvowles** [comment]
HI @michpohl please try swapping to 5.11 once it hits Central and hopefully that will sort out the issue for you. It has required an update of the two versions (3.x and 4.x) of this library and the main generator :-)

If its all good, please feel free to close the issue :-)

**Comment by michpohl** [comment]
Thank you @rvowles!
With these changes, all works as expected - errors are gone!
