### ISSUE TITLE
Any chance of upgrading to DIO 5?

### ISSUE THREAD

**Issue by MagnusJohansson** [dart-ogurets/openapi_dart_common#8]
When I try to use dio 5.0.1 in my project , I get this:

> Because openapi_dart_common 4.1.2 depends on dio ^4.0.0 and no versions of openapi_dart_common match >4.1.2 <5.0.0, openapi_dart_common ^4.1.2 requires dio ^4.0.0.

Any chance of upgrading this package to use dio v5?

**Comment by rvowles** [comment]
Every chance! I didn't realise 5.x was out :-) Thanks for the issue report.

**Comment by rvowles** [comment]
@MagnusJohansson can you please pull the branches for `dio5-upgrade` please and give it a try - you can see how you can override the path: import for the openAPI. 

I have tried this on FeatureHub and it seems to work a treat, but please let me know just in case there are issues with stuff we don't use.

**Comment by MagnusJohansson** [comment]
Hi, thanks for the quick response and action.

I have now used the branch for a while, I cannot see any issues.

I updated my (main app) pubspec.yaml (and the generated API project): 
``` yaml
  dio: ^5.0.1 
....
  openapi_dart_common:
    git:
      url: https://github.com/dart-ogurets/openapi_dart_common.git
      ref: dio5-upgrade
 ```     

I see no issues, the only customization I have is a custom delegate:
``` dart
class CustomDioClientDelegate implements DioClientDelegate { 
...
}
```
That I use in my inherited  custom API client (to inject bearer token, and what not) using an InterceptorsWrapper:

``` dart
class MyAPIClient extends ApiClient {
  final _firebaseService = Get.find<FirebaseService>();
  final _telemetryService = Get.find<TelemetryService>();
  final traceParentHeader = "traceparent";

  static final MyAPIClient _instance = MyAPIClient ._privateConstructor();

  factory MyAPIClient () => _instance;

  MyAPIClient ._privateConstructor() : super(basePath: gApiBaseUrl!) {
    apiClientDelegate = CustomDioClientDelegate();

    final dioDelegate = apiClientDelegate as CustomDioClientDelegate;
    const uuid = Uuid();
    var appName = "";
    var appVersion = "";

    PackageInfo.fromPlatform().then((packageInfo2) {
      appName = packageInfo2.appName;
      appVersion = packageInfo2.version;
    });

    dioDelegate.client.interceptors.add(
      InterceptorsWrapper(
        onRequest: (request, handler) async {
          final token = await _firebaseService.getToken();
          if (token.isNotEmpty) {
            request.headers[HttpHeaders.authorizationHeader] = "Bearer $token";
          }
          request.headers[HttpHeaders.acceptLanguageHeader] =
              Get.locale?.languageCode ?? "en";

          request.headers["X-App-Name"] = appName;
          request.headers["X-App-Version"] = appVersion;
...
...
```

and so far all seems to work as expected.
